## Air Pollution (PM₂.₅) & County-level Health Outcomes in U.S.

## Dataset(s) to be used  
- Air quality dataset (county level): "/Users/huangzhihan/Desktop/zh2695-debug.github.io/air_quality.csv"
- Health outcomes dataset (county level): "/Users/huangzhihan/Desktop/zh2695-debug.github.io/Ranked_Measure_Data_2023.csv" 

## Analysis question  
Across U.S. counties, is there a correlation (or association) between county-level：air pollution (PM₂.₅ exposure) and health outcomes

## Columns that will (likely) be used  
- From air quality dataset: `PM2.5 Wtd AM (µg/m3)` (renamed to `pm25_wtd`), `PM2.5 24-hr (µg/m3)` (renamed to `pm25_24h`)  
- From health dataset: `Poor Physical Health Days`, `Poor Mental Health Days`  
- Geographic / merge keys: `County` (and optionally `State`)  

## Columns used to merge/join datasets  
- Air quality dataset: `County`  
- Health dataset: `County`  

## Hypothesis  
- **H1**: Higher county-level PM₂.₅ exposure (as measured by composite of weighted average and 24-hr) is associated with *higher* average number of physically unhealthy days.  
- **H2**: Higher county-level PM₂.₅ exposure is associated with *higher* average number of mentally unhealthy days.

## Firstly, I import necessary packages.

In [249]:
import os

import pandas as pd

import plotly.express as px

## Because my data is excel, I convert two dataset into csv format.

In [250]:
xlsx_path = "/Users/huangzhihan/Desktop/zh2695-debug.github.io/County Health Data.xlsx"

csv_path = (
    "/Users/huangzhihan/Desktop/zh2695-debug.github.io/Ranked_Measure_Data_2023.csv"
)

df1 = pd.read_excel(xlsx_path, sheet_name="Ranked Measure Data")

df1.to_csv(csv_path, index=False, encoding="utf-8")

In [251]:
xlsx_path = "/Users/huangzhihan/Desktop/zh2695-debug.github.io/ctyfactbook2023.xlsx"

csv_path = "/Users/huangzhihan/Desktop/zh2695-debug.github.io/air_quality.csv"

df2 = pd.read_excel(xlsx_path)

df2.to_csv(csv_path, index=False, encoding="utf-8")

## Second, I begin to process the first dataframe.

In [252]:
df1 = pd.read_csv("Ranked_Measure_Data_2023.csv")

In [253]:
df1.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Premature Death,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Poor or Fair Health,Unnamed: 30,Unnamed: 31,Unnamed: 32,Poor Physical Health Days,Unnamed: 34,Unnamed: 35,Unnamed: 36,Poor Mental Health Days,Unnamed: 38,Unnamed: 39,Unnamed: 40,Low Birthweight,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Adult Smoking,Unnamed: 62,Unnamed: 63,Unnamed: 64,Adult Obesity,Unnamed: 66,Unnamed: 67,Unnamed: 68,Food Environment Index,Unnamed: 70,Physical Inactivity,Unnamed: 72,Unnamed: 73,Unnamed: 74,Access to Exercise Opportunities,Unnamed: 76,Excessive Drinking,Unnamed: 78,Unnamed: 79,Unnamed: 80,Alcohol-Impaired Driving Deaths,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Sexually Transmitted Infections,Unnamed: 88,Unnamed: 89,Teen Births,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Uninsured,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Primary Care Physicians,Unnamed: 115,Unnamed: 116,Unnamed: 117,Dentists,Unnamed: 119,Unnamed: 120,Unnamed: 121,Mental Health Providers,Unnamed: 123,Unnamed: 124,Unnamed: 125,Preventable Hospital Stays,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Mammography Screening,Unnamed: 134,Unnamed: 135,Unnamed: 136,Unnamed: 137,Unnamed: 138,Unnamed: 139,Flu Vaccinations,Unnamed: 141,Unnamed: 142,Unnamed: 143,Unnamed: 144,Unnamed: 145,Unnamed: 146,High School Completion,Unnamed: 148,Unnamed: 149,Unnamed: 150,Unnamed: 151,Unnamed: 152,Some College,Unnamed: 154,Unnamed: 155,Unnamed: 156,Unnamed: 157,Unnamed: 158,Unemployment,Unnamed: 160,Unnamed: 161,Unnamed: 162,Children in Poverty,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171,Income Inequality,Unnamed: 173,Unnamed: 174,Unnamed: 175,Children in Single-Parent Households,Unnamed: 177,Unnamed: 178,Unnamed: 179,Unnamed: 180,Unnamed: 181,Social Associations,Unnamed: 183,Unnamed: 184,Injury Deaths,Unnamed: 186,Unnamed: 187,Unnamed: 188,Unnamed: 189,Unnamed: 190,Unnamed: 191,Unnamed: 192,Unnamed: 193,Unnamed: 194,Unnamed: 195,Unnamed: 196,Unnamed: 197,Unnamed: 198,Unnamed: 199,Unnamed: 200,Unnamed: 201,Unnamed: 202,Unnamed: 203,Unnamed: 204,Air Pollution - Particulate Matter,Unnamed: 206,Drinking Water Violations,Unnamed: 208,Severe Housing Problems,Unnamed: 210,Unnamed: 211,Unnamed: 212,Unnamed: 213,Unnamed: 214,Unnamed: 215,Unnamed: 216,Unnamed: 217,Unnamed: 218,Unnamed: 219,Unnamed: 220,Unnamed: 221,Driving Alone to Work,Unnamed: 223,Unnamed: 224,Unnamed: 225,Unnamed: 226,Unnamed: 227,Unnamed: 228,Unnamed: 229,Unnamed: 230,Unnamed: 231,Unnamed: 232,Unnamed: 233,Unnamed: 234,Unnamed: 235,Unnamed: 236,Unnamed: 237,Unnamed: 238,Unnamed: 239,Unnamed: 240,Long Commute - Driving Alone,Unnamed: 242,Unnamed: 243,Unnamed: 244,Unnamed: 245
0,FIPS,State,County,Unreliable,Deaths,Years of Potential Life Lost Rate,95% CI - Low,95% CI - High,Quartile,YPLL Rate (AIAN),YPLL Rate (AIAN) 95% CI - Low,YPLL Rate (AIAN) 95% CI - High,YPLL Rate (AIAN) Unreliable,YPLL Rate (Asian),YPLL Rate (Asian) 95% CI - Low,YPLL Rate (Asian) 95% CI - High,YPLL Rate (Asian) Unreliable,YPLL Rate (Black),YPLL Rate (Black) 95% CI - Low,YPLL Rate (Black) 95% CI - High,YPLL Rate (Black) Unreliable,YPLL Rate (Hispanic),YPLL Rate (Hispanic) 95% CI - Low,YPLL Rate (Hispanic) 95% CI - High,YPLL Rate (Hispanic) Unreliable,YPLL Rate (White),YPLL Rate (White) 95% CI - Low,YPLL Rate (White) 95% CI - High,YPLL Rate (White) Unreliable,% Fair or Poor Health,95% CI - Low,95% CI - High,Quartile,Average Number of Physically Unhealthy Days,95% CI - Low,95% CI - High,Quartile,Average Number of Mentally Unhealthy Days,95% CI - Low,95% CI - High,Quartile,Unreliable,% Low Birthweight,95% CI - Low,95% CI - High,Quartile,% LBW (AIAN),% LBW (AIAN) 95% CI - Low,% LBW (AIAN) 95% CI - High,% LBW (Asian),% LBW (Asian) 95% CI - Low,% LBW (Asian) 95% CI - High,% LBW (Black),% LBW (Black) 95% CI - Low,% LBW (Black) 95% CI - High,% LBW (Hispanic),% LBW (Hispanic) 95% CI - Low,% LBW (Hispanic) 95% CI - High,% LBW (White),% LBW (White) 95% CI - Low,% LBW (White) 95% CI - High,% Adults Reporting Currently Smoking,95% CI - Low,95% CI - High,Quartile,% Adults with Obesity,95% CI - Low,95% CI - High,Quartile,Food Environment Index,Quartile,% Physically Inactive,95% CI - Low,95% CI - High,Quartile,% With Access to Exercise Opportunities,Quartile,% Excessive Drinking,95% CI - Low,95% CI - High,Quartile,# Alcohol-Impaired Driving Deaths,# Driving Deaths,% Driving Deaths with Alcohol Involvement,95% CI - Low,95% CI - High,Quartile,# Chlamydia Cases,Chlamydia Rate,Quartile,Teen Birth Rate,95% CI - Low,95% CI - High,Quartile,Teen Birth Rate (AIAN),Teen Birth Rate (AIAN) 95% CI - Low,Teen Birth Rate (AIAN) 95% CI - High,Teen Birth Rate (Asian),Teen Birth Rate (Asian) 95% CI - Low,Teen Birth Rate (Asian) 95% CI - High,Teen Birth Rate (Black),Teen Birth Rate (Black) 95% CI - Low,Teen Birth Rate (Black) 95% CI - High,Teen Birth Rate (Hispanic),Teen Birth Rate (Hispanic) 95% CI - Low,Teen Birth Rate (Hispanic) 95% CI - High,Teen Birth Rate (White),Teen Birth Rate (White) 95% CI - Low,Teen Birth Rate (White) 95% CI - High,# Uninsured,% Uninsured,95% CI - Low,95% CI - High,Quartile,# Primary Care Physicians,Primary Care Physicians Rate,Primary Care Physicians Ratio,Quartile,# Dentists,Dentist Rate,Dentist Ratio,Quartile,# Mental Health Providers,Mental Health Provider Rate,Mental Health Provider Ratio,Quartile,Preventable Hospitalization Rate,Quartile,Preventable Hosp. Rate (AIAN),Preventable Hosp. Rate (Asian),Preventable Hosp. Rate (Black),Preventable Hosp. Rate (Hispanic),Preventable Hosp. Rate (White),% with Annual Mammogram,Quartile,% Screened (AIAN),% Screened (Asian),% Screened (Black),% Screened (Hispanic),% Screened (White),% Vaccinated,Quartile,% Vaccinated (AIAN),% Vaccinated (Asian),% Vaccinated (Black),% Vaccinated (Hispanic),% Vaccinated (White),# Completed High School,Population,% Completed High School,95% CI - Low,95% CI - High,Quartile,# Some College,Population,% Some College,95% CI - Low,95% CI - High,Quartile,# Unemployed,Labor Force,% Unemployed,Quartile,% Children in Poverty,95% CI - Low,95% CI - High,Quartile,% Children in Poverty (AIAN),% Children in Poverty (Asian),% Children in Poverty (Black),% Children in Poverty (Hispanic),% Children in Poverty (White),80th Percentile Income,20th Percentile Income,Income Ratio,Quartile,# Children in Single-Parent Households,# Children in Households,% Children in Single-Parent Households,95% CI - Low,95% CI - High,Quartile,# Associations,Social Association Rate,Quartile,# Injury Deaths,Injury Death Rate,95% CI - Low,95% CI - High,Quartile,Injury Death Rate (AIAN),Injury Death Rate (AIAN) 95% CI - Low,Injury Death Rate (AIAN) 95% CI - High,Injury Death Rate (Asian),Injury Death Rate (Asian) 95% CI - Low,Injury Death Rate (Asian) 95% CI - High,Injury Death Rate (Black),Injury Death Rate (Black) 95% CI - Low,Injury Death Rate (Black) 95% CI - High,Injury Death Rate (Hispanic),Injury Death Rate (Hispanic) 95% CI - Low,Injury Death Rate (Hispanic) 95% CI - High,Injury Death Rate (White),Injury Death Rate (White) 95% CI - Low,Injury Death Rate (White) 95% CI - High,Average Daily PM2.5,Quartile,Presence of Water Violation,Quartile,% Severe Housing Problems,95% CI - Low,95% CI - High,Severe Housing Cost Burden,Severe Housing Cost Burden 95% CI - Low,Severe Housing Cost Burden 95% CI - High,Overcrowding,Overcrowding 95% CI - Low,Overcrowding 95% CI - High,Inadequate Facilities,Inadequate Facilities 95% CI - Low,Inadequate Facilities 95% CI - High,Quartile,% Drive Alone to Work,95% CI - Low,95% CI - High,Quartile,% Drive Alone (AIAN),% Drive Alone (AIAN) 95% CI - Low,% Drive Alone (AIAN) 95% CI - High,% Drive Alone (Asian),% Drive Alone (Asian) 95% CI - Low,% Drive Alone (Asian) 95% CI - High,% Drive Alone (Black),% Drive Alone (Black) 95% CI - Low,% Drive Alone (Black) 95% CI - High,% Drive Alone (Hispanic),% Drive Alone (Hispanic) 95% CI - Low,% Drive Alone (Hispanic) 95% CI - High,% Drive Alone (White),% Drive Alone (White) 95% CI - Low,% Drive Alone (White) 95% CI - High,# Workers who Drive Alone,% Long Commute - Drives Alone,95% CI - Low,95% CI - High,Quartile
1,01000,Alabama,NaN,NaN,88086,10350.071456,10246.133257,10454.009654,NaN,5967.1527724,4839.9183327,7094.3872121,NaN,3410.7724121,2945.3678175,3876.1770067,NaN,13245.058385,13022.778798,13467.337973,NaN,5244.4248473,4900.9173186,5587.9323761,NaN,9562.5167175,9438.7153323,9686.3181028,NaN,18.9,17.6,20.3,NaN,3.4824161407,3.2210998691,3.7437324124,NaN,5.0732772786,4.7263855677,5.4201689894,NaN,NaN,10.432760034,10.339305044,10.526215025,NaN,10,8.2660825956,11.733917404,9.3993706389,8.7303460417,10.068395236,15.850874371,15.65037389,16.051374853,7.3173019794,7.0318727435,7.6027312153,8.0298939883,7.9218406141,8.1379473624,19.5,17.9,21.1,NaN,39.3,37.4,41.1,NaN,5.3,NaN,27.8,26.2,29.5,NaN,60.926672265,NaN,16.141626933,14.705210064,17.689255252,NaN,1255,4848,25.886963696,25.178203209,26.600283844,NaN,27075,552.2,NaN,27.598889304,27.287283978,27.91049463,NaN,14.024474082,11.302759566,16.746188599,4.2605315013,3.3783365069,5.3026002539,33.924512458,33.31021318,34.538811736,52.301114366,50.462052297,54.140176435,22.879460065,22.514840646,23.244079484,460936,11.822715693,11.346119949,12.299311438,NaN,3238,65.79252,1520:1,NaN,2454,48.69166,2054:1,NaN,6321,125.41973,797:1,NaN,3599,NaN,7955,2049,4725,3084,3358,36,NaN,34,30,36,27,37,44,NaN,29,45,33,34,46,2983756,3413803,87.402700156,87.191091654,87.614308657,NaN,776360,1262357,61.50082742,60.846058015,62.155596826,NaN,77275,2247001,3.439028287,NaN,22.7,21.746808511,23.653191489,NaN,23.292747485,12.433079297,38.29079181,36.723054506,12.424864598,112484,21729,5.1766763312,NaN,346161,1119928,30.909219164,30.280231918,31.53820641,NaN,5862,11.910925297,NaN,21249,86.9057184,85.737201017,88.074235782,NaN,37.202875251,28.102652155,48.311028,28.17173081,22.930803794,33.412657827,85.849639796,83.615614137,88.083665455,42.609474462,38.719813157,46.499135766,92.050419234,90.573708011,93.527130458,9.3,NaN,NaN,NaN,13.156788792,12.952226642,13.361350941,11.296939615,11.084423305,11.509455925,1.7080724559,1.6227021636,1.7934427481,0.8279373305,0.7766330891,0.8792415719,NaN,83.78249329,83.431442665,84.133543915,NaN,75.514294757,69.965082676,81.063506838,74.519774011,72.648241284,76.391306739,82.964680492,82.309192434,83.620168551,74.762079904,73.063781855,76.460377953,84.903068438,84.506276008,85.299860868,2146674,35,34.523404255,35.476595745,NaN
2,01001,Alabama,Autauga,NaN,836,8027.3947267,7197.6258114,8857.1636419,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11548.535678,9369.1914707,13727.879885,NaN,NaN,NaN,NaN,NaN,7332.5538664,6411.3065913,8253.8011416,NaN,16.9,15,19.2,1,3.4322111963,3.0959820193,3.7440621648,1,4.7973512632,4.5016829156,5.0727011731,1,NaN,9.7381519152,8.8833244441,10.592979386,2,NaN,NaN,NaN,NaN,NaN,NaN,14.496768236,12.399911757,16.593624716,NaN,NaN,NaN,8.3636363636,7.4190740892,9.3081986381,18.3,15.4,21.4,1,37.3,35.7,38.9,1,6.6,3,26.4,23.9,29.1,1,55.537794405,2,16.656260168,15.936707272,17.399588441,4,18,56,32.142857143,25.218646107,39.119228355,3,315,563.8,3,22.976945691,20.363760764,25.590130617,1,NaN,NaN,NaN,NaN,NaN,NaN,29.495380242,23.492905721,36.563961548,NaN,NaN,NaN,21.931674399,18.951125896,24.912222902,4902,10.559420977,9.0104848065,12.108357147,1,25,44.52756,2246:1,2,19,32.15162,3110:1,2,21,35.536,2814:1,3,4372,4,NaN,15789,7325,NaN,3824,38,1,NaN,33,31,20,40,42,2,NaN,25,35,29,43,35488,39614,89.584490332,87.892162752,91.276817911,1,9048,15178,59.61259718,53.080798885,66.144395475,1,742,26341,2.8169014085,2,16.1,10.5,21.7,1,NaN,9.756097561,40.766666667,19.178082192,11.28945384,114380,23857,4.7943999665,2,3694,13801,26.766176364,20.441327799,33.091024929,2,71,12.645827767,2,191,68.573069812,58.847994355,78.298145269,1,NaN,NaN,NaN,NaN,NaN,NaN,62.533500089,43.556874044,86.968960817,NaN,NaN,NaN,72.628234226,61.082015963,84.174452489,10,4,No,1,14.442626782,11.97723627,16.908017294,12.635805385,10.313635373,14.957975397,1.12175742,0.4608329761,1.7826818638,1.6358962374,0.741281643,2.5305108319,4,86.401088518,83.574149983,89.228027053,3,NaN,NaN,NaN,NaN,NaN,NaN,81.302350716,72.787492913,89.817208519,NaN,NaN,NaN,83.056872038,77.72506063,88.388683445,26458,41.6,36.414625156,46.785374844,3
3,01003,Alabama,Baldwin,NaN,3377,8118.3582061,7666.8741011,8569.8423111,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11603.143788,9970.8024853,13235.48509,NaN,4590.5480416,3232.1694627,6327.4657813,NaN,8058.6091455,7555.2951029,8561.923188,NaN,14.9,12.8,17,1,3.2761769521,2.9506709987,3.6093992372,1,4.7537497106,4.4654610661,5.0571195082,1,NaN,8.3857311835,7.957089137,8.81437323,1,NaN,NaN,NaN,8.8669950739,4.9564784969,12.777511651,15.002698327,13.376754194,16.628642461,6.468401487,5.1538651617,7.7829378123,7.6372315036,7.1729248778,8.1015381294,16.9,13.8,20,1,32.6,31.1,34.2,1,7.5,1,23.2,20.4,26,1,65.735846777,1,18.965166014,18.20699452,19.749129141,4,57,177,32.203389831,28.423815674,36.009851621,3,786,352.1,2,23.734320007,22.300069556,25.168570458,1,NaN,NaN,NaN,NaN,NaN,NaN,30.64738292,26.145030722,35.149735118,41.714947856,33.847463307,49.582432405,22.096217922,20.521099837,23.671336008,19391,10.874880826,9.4450935915,12.30466806,1,150,65.42018999999999,1529:1,1,114,47.64014,2099:1,1,250,104.47398999999999,957:1,2,2864,1,NaN,2048,4455,893,2789,39,1,38,33,31,30,39,47,1,39,47,35,37,48,147422,161977,91.014156331,90.072841309,91.955471353,1,34799,52642,66.105011208,62.126610675,70.08341174,1,2946,99427,2.9629778632,2,16.4,12.468085106,20.331914894,1,73.015873016,7.7669902913,26.249530252,27.836292507,7.4958768554,126028,29304,4.3007098007,1,9151,48938,18.699170379,15.789013121,21.609327636,1,220,9.5949617728,3,817,74.835078875,69.7035088,79.966648949,1,NaN,NaN,NaN,NaN,NaN,NaN,63.239043585,48.594617449,80.910207873,25.90880102,13.795345366,44.304838804,80.226024322,74.437829222,86.014219423,7.6,1,Yes,4,12.238971951,10.855621196,13.622322706,10.561056106,9.2669318433,11.855180368,1.2912393426,0.8711269785,1.7113517068,0.642530582,0.34688537,0.938175794,3,81.40185095,79.929245319,82.87445658,1,NaN,NaN,NaN,NaN,NaN,NaN,82.651140908,69.646604624,95.655677193,57.737813535,48.583972975,66.891654096,80.332636926,78.502319052,82.162954799,102650,37.6,34.962525866,40.237474134,2
4,01005,Alabama,Barbour,NaN,539,12876.760319,11149.914146,14603.606492,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15533.506861,12930.989032,18136.024691,NaN,NaN,NaN,NaN,NaN,9950.1512653,7691.2667845,12209.035746,NaN,27.5,25.2,30,4,4.6054318631,4.278386076,4.9370408429,4,4.9548545646,4.7218857494,5.1903217625,1,NaN,11.914672216,10.466326576,13.363017857,3,NaN,NaN,NaN,NaN,NaN,NaN,15.746606335,13.598963196,17.894249474,NaN,NaN,NaN,7.3667711599,5.3397059375,9.3938363823,25.9,23.2,28.6,4,46.4,45,47.8,4,5.8,4,35.7,33.2,38.1,4,54.842802204,2,13.428772645,12.846480537,14.034104382,1,12,32,37.5,28.328681558,46.401415144,4,155,627.9,3,34.700315457,29.405540304,39.995090611,3,NaN,NaN,NaN,NaN,NaN,NaN,34.45664521,27.742341347,42.305124921,76.923076923,44.810527012,123.16129781,30.335284726,22.97564841,39.302879938,2337,14.368275438,12.104445651,16.632105225,4,8,32.53487,3074:1,3,8,32.04615,3121:1,2,6,24.03461,4161:1,4,3559,2,NaN,NaN,4796,NaN,2957,41,1,NaN,NaN,46,NaN,40,40,2,NaN,NaN,34,NaN,42,13617,17995,75.671019728,73.303950057,78.038089399,4,2605,6744,38.626927639,32.700758644,44.553096635,4,469,8197,5.7216054654,4,35.1,22.827659574,47.372340426,4,NaN,NaN,57.942898975,67.265469062,13.720022309,79460,15338,5.1805972095,3,2845,5261,54.07717164,47.241662293,60.912680988,4,23,9.3537760787,3,103,82.143056519,66.279216636,98.006896402,1,NaN,NaN,NaN,NaN,NaN,NaN,82.159817277,60.980599993,108.31747648,NaN,NaN,NaN,86.413992154,64.138130584,113.92607571,9.4,3,Yes,4,16.21187801,13.206464639,19.21729138,13.464345873,10.82042148,16.108270266,3.8523274478,1.8320382169,5.8726166788,0.5885500268,0.1172118745,1.059888179,4,83.122562345,79.819449935,86.425674755,2,NaN,NaN,NaN,NaN,NaN,NaN,79.354669465,72.960257711,85.749081219,NaN,NaN,NaN,84.436758893,80.659917808,88.213599979,8461,36.5,30.560452421,42.439547579,2

In [254]:
df1 = df1.rename(columns={"Unnamed: 1": "State", "Unnamed: 2": "County"})

In [255]:
df1.head()

,Unnamed: 0,State,County,Premature Death,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Poor or Fair Health,Unnamed: 30,Unnamed: 31,Unnamed: 32,Poor Physical Health Days,Unnamed: 34,Unnamed: 35,Unnamed: 36,Poor Mental Health Days,Unnamed: 38,Unnamed: 39,Unnamed: 40,Low Birthweight,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Adult Smoking,Unnamed: 62,Unnamed: 63,Unnamed: 64,Adult Obesity,Unnamed: 66,Unnamed: 67,Unnamed: 68,Food Environment Index,Unnamed: 70,Physical Inactivity,Unnamed: 72,Unnamed: 73,Unnamed: 74,Access to Exercise Opportunities,Unnamed: 76,Excessive Drinking,Unnamed: 78,Unnamed: 79,Unnamed: 80,Alcohol-Impaired Driving Deaths,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Sexually Transmitted Infections,Unnamed: 88,Unnamed: 89,Teen Births,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Uninsured,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Primary Care Physicians,Unnamed: 115,Unnamed: 116,Unnamed: 117,Dentists,Unnamed: 119,Unnamed: 120,Unnamed: 121,Mental Health Providers,Unnamed: 123,Unnamed: 124,Unnamed: 125,Preventable Hospital Stays,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Mammography Screening,Unnamed: 134,Unnamed: 135,Unnamed: 136,Unnamed: 137,Unnamed: 138,Unnamed: 139,Flu Vaccinations,Unnamed: 141,Unnamed: 142,Unnamed: 143,Unnamed: 144,Unnamed: 145,Unnamed: 146,High School Completion,Unnamed: 148,Unnamed: 149,Unnamed: 150,Unnamed: 151,Unnamed: 152,Some College,Unnamed: 154,Unnamed: 155,Unnamed: 156,Unnamed: 157,Unnamed: 158,Unemployment,Unnamed: 160,Unnamed: 161,Unnamed: 162,Children in Poverty,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171,Income Inequality,Unnamed: 173,Unnamed: 174,Unnamed: 175,Children in Single-Parent Households,Unnamed: 177,Unnamed: 178,Unnamed: 179,Unnamed: 180,Unnamed: 181,Social Associations,Unnamed: 183,Unnamed: 184,Injury Deaths,Unnamed: 186,Unnamed: 187,Unnamed: 188,Unnamed: 189,Unnamed: 190,Unnamed: 191,Unnamed: 192,Unnamed: 193,Unnamed: 194,Unnamed: 195,Unnamed: 196,Unnamed: 197,Unnamed: 198,Unnamed: 199,Unnamed: 200,Unnamed: 201,Unnamed: 202,Unnamed: 203,Unnamed: 204,Air Pollution - Particulate Matter,Unnamed: 206,Drinking Water Violations,Unnamed: 208,Severe Housing Problems,Unnamed: 210,Unnamed: 211,Unnamed: 212,Unnamed: 213,Unnamed: 214,Unnamed: 215,Unnamed: 216,Unnamed: 217,Unnamed: 218,Unnamed: 219,Unnamed: 220,Unnamed: 221,Driving Alone to Work,Unnamed: 223,Unnamed: 224,Unnamed: 225,Unnamed: 226,Unnamed: 227,Unnamed: 228,Unnamed: 229,Unnamed: 230,Unnamed: 231,Unnamed: 232,Unnamed: 233,Unnamed: 234,Unnamed: 235,Unnamed: 236,Unnamed: 237,Unnamed: 238,Unnamed: 239,Unnamed: 240,Long Commute - Driving Alone,Unnamed: 242,Unnamed: 243,Unnamed: 244,Unnamed: 245
0,FIPS,State,County,Unreliable,Deaths,Years of Potential Life Lost Rate,95% CI - Low,95% CI - High,Quartile,YPLL Rate (AIAN),YPLL Rate (AIAN) 95% CI - Low,YPLL Rate (AIAN) 95% CI - High,YPLL Rate (AIAN) Unreliable,YPLL Rate (Asian),YPLL Rate (Asian) 95% CI - Low,YPLL Rate (Asian) 95% CI - High,YPLL Rate (Asian) Unreliable,YPLL Rate (Black),YPLL Rate (Black) 95% CI - Low,YPLL Rate (Black) 95% CI - High,YPLL Rate (Black) Unreliable,YPLL Rate (Hispanic),YPLL Rate (Hispanic) 95% CI - Low,YPLL Rate (Hispanic) 95% CI - High,YPLL Rate (Hispanic) Unreliable,YPLL Rate (White),YPLL Rate (White) 95% CI - Low,YPLL Rate (White) 95% CI - High,YPLL Rate (White) Unreliable,% Fair or Poor Health,95% CI - Low,95% CI - High,Quartile,Average Number of Physically Unhealthy Days,95% CI - Low,95% CI - High,Quartile,Average Number of Mentally Unhealthy Days,95% CI - Low,95% CI - High,Quartile,Unreliable,% Low Birthweight,95% CI - Low,95% CI - High,Quartile,% LBW (AIAN),% LBW (AIAN) 95% CI - Low,% LBW (AIAN) 95% CI - High,% LBW (Asian),% LBW (Asian) 95% CI - Low,% LBW (Asian) 95% CI - High,% LBW (Black),% LBW (Black) 95% CI - Low,% LBW (Black) 95% CI - High,% LBW (Hispanic),% LBW (Hispanic) 95% CI - Low,% LBW (Hispanic) 95% CI - High,% LBW (White),% LBW (White) 95% CI - Low,% LBW (White) 95% CI - High,% Adults Reporting Currently Smoking,95% CI - Low,95% CI - High,Quartile,% Adults with Obesity,95% CI - Low,95% CI - High,Quartile,Food Environment Index,Quartile,% Physically Inactive,95% CI - Low,95% CI - High,Quartile,% With Access to Exercise Opportunities,Quartile,% Excessive Drinking,95% CI - Low,95% CI - High,Quartile,# Alcohol-Impaired Driving Deaths,# Driving Deaths,% Driving Deaths with Alcohol Involvement,95% CI - Low,95% CI - High,Quartile,# Chlamydia Cases,Chlamydia Rate,Quartile,Teen Birth Rate,95% CI - Low,95% CI - High,Quartile,Teen Birth Rate (AIAN),Teen Birth Rate (AIAN) 95% CI - Low,Teen Birth Rate (AIAN) 95% CI - High,Teen Birth Rate (Asian),Teen Birth Rate (Asian) 95% CI - Low,Teen Birth Rate (Asian) 95% CI - High,Teen Birth Rate (Black),Teen Birth Rate (Black) 95% CI - Low,Teen Birth Rate (Black) 95% CI - High,Teen Birth Rate (Hispanic),Teen Birth Rate (Hispanic) 95% CI - Low,Teen Birth Rate (Hispanic) 95% CI - High,Teen Birth Rate (White),Teen Birth Rate (White) 95% CI - Low,Teen Birth Rate (White) 95% CI - High,# Uninsured,% Uninsured,95% CI - Low,95% CI - High,Quartile,# Primary Care Physicians,Primary Care Physicians Rate,Primary Care Physicians Ratio,Quartile,# Dentists,Dentist Rate,Dentist Ratio,Quartile,# Mental Health Providers,Mental Health Provider Rate,Mental Health Provider Ratio,Quartile,Preventable Hospitalization Rate,Quartile,Preventable Hosp. Rate (AIAN),Preventable Hosp. Rate (Asian),Preventable Hosp. Rate (Black),Preventable Hosp. Rate (Hispanic),Preventable Hosp. Rate (White),% with Annual Mammogram,Quartile,% Screened (AIAN),% Screened (Asian),% Screened (Black),% Screened (Hispanic),% Screened (White),% Vaccinated,Quartile,% Vaccinated (AIAN),% Vaccinated (Asian),% Vaccinated (Black),% Vaccinated (Hispanic),% Vaccinated (White),# Completed High School,Population,% Completed High School,95% CI - Low,95% CI - High,Quartile,# Some College,Population,% Some College,95% CI - Low,95% CI - High,Quartile,# Unemployed,Labor Force,% Unemployed,Quartile,% Children in Poverty,95% CI - Low,95% CI - High,Quartile,% Children in Poverty (AIAN),% Children in Poverty (Asian),% Children in Poverty (Black),% Children in Poverty (Hispanic),% Children in Poverty (White),80th Percentile Income,20th Percentile Income,Income Ratio,Quartile,# Children in Single-Parent Households,# Children in Households,% Children in Single-Parent Households,95% CI - Low,95% CI - High,Quartile,# Associations,Social Association Rate,Quartile,# Injury Deaths,Injury Death Rate,95% CI - Low,95% CI - High,Quartile,Injury Death Rate (AIAN),Injury Death Rate (AIAN) 95% CI - Low,Injury Death Rate (AIAN) 95% CI - High,Injury Death Rate (Asian),Injury Death Rate (Asian) 95% CI - Low,Injury Death Rate (Asian) 95% CI - High,Injury Death Rate (Black),Injury Death Rate (Black) 95% CI - Low,Injury Death Rate (Black) 95% CI - High,Injury Death Rate (Hispanic),Injury Death Rate (Hispanic) 95% CI - Low,Injury Death Rate (Hispanic) 95% CI - High,Injury Death Rate (White),Injury Death Rate (White) 95% CI - Low,Injury Death Rate (White) 95% CI - High,Average Daily PM2.5,Quartile,Presence of Water Violation,Quartile,% Severe Housing Problems,95% CI - Low,95% CI - High,Severe Housing Cost Burden,Severe Housing Cost Burden 95% CI - Low,Severe Housing Cost Burden 95% CI - High,Overcrowding,Overcrowding 95% CI - Low,Overcrowding 95% CI - High,Inadequate Facilities,Inadequate Facilities 95% CI - Low,Inadequate Facilities 95% CI - High,Quartile,% Drive Alone to Work,95% CI - Low,95% CI - High,Quartile,% Drive Alone (AIAN),% Drive Alone (AIAN) 95% CI - Low,% Drive Alone (AIAN) 95% CI - High,% Drive Alone (Asian),% Drive Alone (Asian) 95% CI - Low,% Drive Alone (Asian) 95% CI - High,% Drive Alone (Black),% Drive Alone (Black) 95% CI - Low,% Drive Alone (Black) 95% CI - High,% Drive Alone (Hispanic),% Drive Alone (Hispanic) 95% CI - Low,% Drive Alone (Hispanic) 95% CI - High,% Drive Alone (White),% Drive Alone (White) 95% CI - Low,% Drive Alone (White) 95% CI - High,# Workers who Drive Alone,% Long Commute - Drives Alone,95% CI - Low,95% CI - High,Quartile
1,01000,Alabama,NaN,NaN,88086,10350.071456,10246.133257,10454.009654,NaN,5967.1527724,4839.9183327,7094.3872121,NaN,3410.7724121,2945.3678175,3876.1770067,NaN,13245.058385,13022.778798,13467.337973,NaN,5244.4248473,4900.9173186,5587.9323761,NaN,9562.5167175,9438.7153323,9686.3181028,NaN,18.9,17.6,20.3,NaN,3.4824161407,3.2210998691,3.7437324124,NaN,5.0732772786,4.7263855677,5.4201689894,NaN,NaN,10.432760034,10.339305044,10.526215025,NaN,10,8.2660825956,11.733917404,9.3993706389,8.7303460417,10.068395236,15.850874371,15.65037389,16.051374853,7.3173019794,7.0318727435,7.6027312153,8.0298939883,7.9218406141,8.1379473624,19.5,17.9,21.1,NaN,39.3,37.4,41.1,NaN,5.3,NaN,27.8,26.2,29.5,NaN,60.926672265,NaN,16.141626933,14.705210064,17.689255252,NaN,1255,4848,25.886963696,25.178203209,26.600283844,NaN,27075,552.2,NaN,27.598889304,27.287283978,27.91049463,NaN,14.024474082,11.302759566,16.746188599,4.2605315013,3.3783365069,5.3026002539,33.924512458,33.31021318,34.538811736,52.301114366,50.462052297,54.140176435,22.879460065,22.514840646,23.244079484,460936,11.822715693,11.346119949,12.299311438,NaN,3238,65.79252,1520:1,NaN,2454,48.69166,2054:1,NaN,6321,125.41973,797:1,NaN,3599,NaN,7955,2049,4725,3084,3358,36,NaN,34,30,36,27,37,44,NaN,29,45,33,34,46,2983756,3413803,87.402700156,87.191091654,87.614308657,NaN,776360,1262357,61.50082742,60.846058015,62.155596826,NaN,77275,2247001,3.439028287,NaN,22.7,21.746808511,23.653191489,NaN,23.292747485,12.433079297,38.29079181,36.723054506,12.424864598,112484,21729,5.1766763312,NaN,346161,1119928,30.909219164,30.280231918,31.53820641,NaN,5862,11.910925297,NaN,21249,86.9057184,85.737201017,88.074235782,NaN,37.202875251,28.102652155,48.311028,28.17173081,22.930803794,33.412657827,85.849639796,83.615614137,88.083665455,42.609474462,38.719813157,46.499135766,92.050419234,90.573708011,93.527130458,9.3,NaN,NaN,NaN,13.156788792,12.952226642,13.361350941,11.296939615,11.084423305,11.509455925,1.7080724559,1.6227021636,1.7934427481,0.8279373305,0.7766330891,0.8792415719,NaN,83.78249329,83.431442665,84.133543915,NaN,75.514294757,69.965082676,81.063506838,74.519774011,72.648241284,76.391306739,82.964680492,82.309192434,83.620168551,74.762079904,73.063781855,76.460377953,84.903068438,84.506276008,85.299860868,2146674,35,34.523404255,35.476595745,NaN
2,01001,Alabama,Autauga,NaN,836,8027.3947267,7197.6258114,8857.1636419,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11548.535678,9369.1914707,13727.879885,NaN,NaN,NaN,NaN,NaN,7332.5538664,6411.3065913,8253.8011416,NaN,16.9,15,19.2,1,3.4322111963,3.0959820193,3.7440621648,1,4.7973512632,4.5016829156,5.0727011731,1,NaN,9.7381519152,8.8833244441,10.592979386,2,NaN,NaN,NaN,NaN,NaN,NaN,14.496768236,12.399911757,16.593624716,NaN,NaN,NaN,8.3636363636,7.4190740892,9.3081986381,18.3,15.4,21.4,1,37.3,35.7,38.9,1,6.6,3,26.4,23.9,29.1,1,55.537794405,2,16.656260168,15.936707272,17.399588441,4,18,56,32.142857143,25.218646107,39.119228355,3,315,563.8,3,22.976945691,20.363760764,25.590130617,1,NaN,NaN,NaN,NaN,NaN,NaN,29.495380242,23.492905721,36.563961548,NaN,NaN,NaN,21.931674399,18.951125896,24.912222902,4902,10.559420977,9.0104848065,12.108357147,1,25,44.52756,2246:1,2,19,32.15162,3110:1,2,21,35.536,2814:1,3,4372,4,NaN,15789,7325,NaN,3824,38,1,NaN,33,31,20,40,42,2,NaN,25,35,29,43,35488,39614,89.584490332,87.892162752,91.276817911,1,9048,15178,59.61259718,53.080798885,66.144395475,1,742,26341,2.8169014085,2,16.1,10.5,21.7,1,NaN,9.756097561,40.766666667,19.178082192,11.28945384,114380,23857,4.7943999665,2,3694,13801,26.766176364,20.441327799,33.091024929,2,71,12.645827767,2,191,68.573069812,58.847994355,78.298145269,1,NaN,NaN,NaN,NaN,NaN,NaN,62.533500089,43.556874044,86.968960817,NaN,NaN,NaN,72.628234226,61.082015963,84.174452489,10,4,No,1,14.442626782,11.97723627,16.908017294,12.635805385,10.313635373,14.957975397,1.12175742,0.4608329761,1.7826818638,1.6358962374,0.741281643,2.5305108319,4,86.401088518,83.574149983,89.228027053,3,NaN,NaN,NaN,NaN,NaN,NaN,81.302350716,72.787492913,89.817208519,NaN,NaN,NaN,83.056872038,77.72506063,88.388683445,26458,41.6,36.414625156,46.785374844,3
3,01003,Alabama,Baldwin,NaN,3377,8118.3582061,7666.8741011,8569.8423111,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11603.143788,9970.8024853,13235.48509,NaN,4590.5480416,3232.1694627,6327.4657813,NaN,8058.6091455,7555.2951029,8561.923188,NaN,14.9,12.8,17,1,3.2761769521,2.9506709987,3.6093992372,1,4.7537497106,4.4654610661,5.0571195082,1,NaN,8.3857311835,7.957089137,8.81437323,1,NaN,NaN,NaN,8.8669950739,4.9564784969,12.777511651,15.002698327,13.376754194,16.628642461,6.468401487,5.1538651617,7.7829378123,7.6372315036,7.1729248778,8.1015381294,16.9,13.8,20,1,32.6,31.1,34.2,1,7.5,1,23.2,20.4,26,1,65.735846777,1,18.965166014,18.20699452,19.749129141,4,57,177,32.203389831,28.423815674,36.009851621,3,786,352.1,2,23.734320007,22.300069556,25.168570458,1,NaN,NaN,NaN,NaN,NaN,NaN,30.64738292,26.145030722,35.149735118,41.714947856,33.847463307,49.582432405,22.096217922,20.521099837,23.671336008,19391,10.874880826,9.4450935915,12.30466806,1,150,65.42018999999999,1529:1,1,114,47.64014,2099:1,1,250,104.47398999999999,957:1,2,2864,1,NaN,2048,4455,893,2789,39,1,38,33,31,30,39,47,1,39,47,35,37,48,147422,161977,91.014156331,90.072841309,91.955471353,1,34799,52642,66.105011208,62.126610675,70.08341174,1,2946,99427,2.9629778632,2,16.4,12.468085106,20.331914894,1,73.015873016,7.7669902913,26.249530252,27.836292507,7.4958768554,126028,29304,4.3007098007,1,9151,48938,18.699170379,15.789013121,21.609327636,1,220,9.5949617728,3,817,74.835078875,69.7035088,79.966648949,1,NaN,NaN,NaN,NaN,NaN,NaN,63.239043585,48.594617449,80.910207873,25.90880102,13.795345366,44.304838804,80.226024322,74.437829222,86.014219423,7.6,1,Yes,4,12.238971951,10.855621196,13.622322706,10.561056106,9.2669318433,11.855180368,1.2912393426,0.8711269785,1.7113517068,0.642530582,0.34688537,0.938175794,3,81.40185095,79.929245319,82.87445658,1,NaN,NaN,NaN,NaN,NaN,NaN,82.651140908,69.646604624,95.655677193,57.737813535,48.583972975,66.891654096,80.332636926,78.502319052,82.162954799,102650,37.6,34.962525866,40.237474134,2
4,01005,Alabama,Barbour,NaN,539,12876.760319,11149.914146,14603.606492,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15533.506861,12930.989032,18136.024691,NaN,NaN,NaN,NaN,NaN,9950.1512653,7691.2667845,12209.035746,NaN,27.5,25.2,30,4,4.6054318631,4.278386076,4.9370408429,4,4.9548545646,4.7218857494,5.1903217625,1,NaN,11.914672216,10.466326576,13.363017857,3,NaN,NaN,NaN,NaN,NaN,NaN,15.746606335,13.598963196,17.894249474,NaN,NaN,NaN,7.3667711599,5.3397059375,9.3938363823,25.9,23.2,28.6,4,46.4,45,47.8,4,5.8,4,35.7,33.2,38.1,4,54.842802204,2,13.428772645,12.846480537,14.034104382,1,12,32,37.5,28.328681558,46.401415144,4,155,627.9,3,34.700315457,29.405540304,39.995090611,3,NaN,NaN,NaN,NaN,NaN,NaN,34.45664521,27.742341347,42.305124921,76.923076923,44.810527012,123.16129781,30.335284726,22.97564841,39.302879938,2337,14.368275438,12.104445651,16.632105225,4,8,32.53487,3074:1,3,8,32.04615,3121:1,2,6,24.03461,4161:1,4,3559,2,NaN,NaN,4796,NaN,2957,41,1,NaN,NaN,46,NaN,40,40,2,NaN,NaN,34,NaN,42,13617,17995,75.671019728,73.303950057,78.038089399,4,2605,6744,38.626927639,32.700758644,44.553096635,4,469,8197,5.7216054654,4,35.1,22.827659574,47.372340426,4,NaN,NaN,57.942898975,67.265469062,13.720022309,79460,15338,5.1805972095,3,2845,5261,54.07717164,47.241662293,60.912680988,4,23,9.3537760787,3,103,82.143056519,66.279216636,98.006896402,1,NaN,NaN,NaN,NaN,NaN,NaN,82.159817277,60.980599993,108.31747648,NaN,NaN,NaN,86.413992154,64.138130584,113.92607571,9.4,3,Yes,4,16.21187801,13.206464639,19.21729138,13.464345873,10.82042148,16.108270266,3.8523274478,1.8320382169,5.8726166788,0.5885500268,0.1172118745,1.059888179,4,83.122562345,79.819449935,86.425674755,2,NaN,NaN,NaN,NaN,NaN,NaN,79.354669465,72.960257711,85.749081219,NaN,NaN,NaN,84.436758893,80.659917808,88.213599979,8461,36.5,30.560452421,42.439547579,2

## I extracted the useful columns from dataframe.

In [256]:
df1 = df1[
    [
        "State",
        "County",
        "Air Pollution - Particulate Matter",
        "Premature Death",
        "Poor Physical Health Days",
        "Poor Mental Health Days",
    ]
]

In [257]:
df1.head()

,State,County,Air Pollution - Particulate Matter,Premature Death,Poor Physical Health Days,Poor Mental Health Days
0,State,County,Average Daily PM2.5,Unreliable,Average Number of Physically Unhealthy Days,Average Number of Mentally Unhealthy Days
1,Alabama,NaN,9.3,NaN,3.4824161407,5.0732772786
2,Alabama,Autauga,10,NaN,3.4322111963,4.7973512632
3,Alabama,Baldwin,7.6,NaN,3.2761769521,4.7537497106
4,Alabama,Barbour,9.4,NaN,4.6054318631,4.9548545646

In [258]:
df1.drop("Premature Death", axis=1, inplace=True)

In [259]:
df1.head()

,State,County,Air Pollution - Particulate Matter,Poor Physical Health Days,Poor Mental Health Days
0,State,County,Average Daily PM2.5,Average Number of Physically Unhealthy Days,Average Number of Mentally Unhealthy Days
1,Alabama,NaN,9.3,3.4824161407,5.0732772786
2,Alabama,Autauga,10,3.4322111963,4.7973512632
3,Alabama,Baldwin,7.6,3.2761769521,4.7537497106
4,Alabama,Barbour,9.4,4.6054318631,4.9548545646

## Third, I processed the second dataframe.

In [260]:
df2 = pd.read_csv("air_quality.csv")
df2.columns

Index(['State', 'County', 'County FIPS Code', '2010 Population',
       'CO          8-hr (ppm)', 'Pb           3-mo (µg/m3)',
       'NO2         AM (ppb)', 'NO2          1-hr (ppb)',
       'O3            8-hr (ppm)', 'PM10        24-hr (µg/m3) ',
       'PM2.5     Wtd AM (µg/m3) ', 'PM2.5     24-hr (µg/m3) ',
       'SO2         1-hr (ppb)'],
      dtype='object')

## Because the original columns' names are so complicated, I rename them to make them read easier.

In [261]:
df2.rename(
    columns={
        "PM2.5     Wtd AM (µg/m3) ": "pm25_wtd",
        "PM2.5     24-hr (µg/m3) ": "pm25_24h",
    },
    inplace=True,
)
df2.head()

,State,County,County FIPS Code,2010 Population,CO 8-hr (ppm),Pb 3-mo (µg/m3),NO2 AM (ppb),NO2 1-hr (ppb),O3 8-hr (ppm),PM10 24-hr (µg/m3),pm25_wtd,pm25_24h,SO2 1-hr (ppb)
0,Alabama,Baldwin County,1003.0,182265.0,ND,ND,ND,ND,0.065,ND,7.6,18,ND
1,Alabama,Clay County,1027.0,13932.0,ND,ND,ND,ND,ND,ND,IN,IN,ND
2,Alabama,Colbert County,1033.0,54428.0,ND,ND,ND,ND,ND,ND,IN,IN,ND
3,Alabama,DeKalb County,1049.0,71109.0,ND,ND,ND,ND,0.066,ND,8.9,21,ND
4,Alabama,Elmore County,1051.0,79303.0,ND,ND,ND,ND,0.061,ND,ND,ND,ND

## To assign weights to the two different PM₂.₅ metrics.
Prior epidemiological studies suggest that both chronic exposure to fine particulate matter (PM₂.₅) and short-term high-concentration events may contribute to adverse health outcomes such as respiratory illness, cardiovascular stress, and reduced general well-being.  
Because my analysis examines county-level health metrics , I believe that a composite exposure measure that combines long-term pollution burden and potential acute spikes better reflects residents’ exposure than either metric alone.  
Thus, I construct a composite PM₂.₅ measure as:
new_pm2.5 = 0.7 * annual_avg_PM2.5 + 0.3 * daily_24h_PM2.5

In [262]:
df2["pm25_wtd"] = pd.to_numeric(df2["pm25_wtd"], errors="coerce")
df2["pm25_24h"] = pd.to_numeric(df2["pm25_24h"], errors="coerce")

w1 = 0.7
w2 = 0.3

df2["new_pm2.5"] = df2["pm25_wtd"] * w1 + w2 * df2["pm25_24h"]
df2.head()

,State,County,County FIPS Code,2010 Population,CO 8-hr (ppm),Pb 3-mo (µg/m3),NO2 AM (ppb),NO2 1-hr (ppb),O3 8-hr (ppm),PM10 24-hr (µg/m3),pm25_wtd,pm25_24h,SO2 1-hr (ppb),new_pm2.5
0,Alabama,Baldwin County,1003.0,182265.0,ND,ND,ND,ND,0.065,ND,7.6,18.0,ND,10.72
1,Alabama,Clay County,1027.0,13932.0,ND,ND,ND,ND,ND,ND,NaN,NaN,ND,NaN
2,Alabama,Colbert County,1033.0,54428.0,ND,ND,ND,ND,ND,ND,NaN,NaN,ND,NaN
3,Alabama,DeKalb County,1049.0,71109.0,ND,ND,ND,ND,0.066,ND,8.9,21.0,ND,12.53
4,Alabama,Elmore County,1051.0,79303.0,ND,ND,ND,ND,0.061,ND,NaN,NaN,ND,NaN

## I keep the necessary columns

In [263]:
dfpm25 = df2[["State", "County", "new_pm2.5"]]
dfpm25.head()

     State          County  new_pm2.5
0  Alabama  Baldwin County      10.72
1  Alabama     Clay County        NaN
2  Alabama  Colbert County        NaN
3  Alabama   DeKalb County      12.53
4  Alabama   Elmore County        NaN

## I merged two dataframe on "Country", so that I can process the one dataframe and draw a chart.

In [264]:
newdf = pd.merge(df1, dfpm25, on="County", how="outer")
newdf.head()

,State_x,County,Air Pollution - Particulate Matter,Poor Physical Health Days,Poor Mental Health Days,State_y,new_pm2.5
0,South Carolina,Abbeville,9.2,3.990457608,5.0897933139,NaN,NaN
1,Louisiana,Acadia,8.6,4.3123100071,6.1451431097,NaN,NaN
2,Virginia,Accomack,6.9,3.9489105646,4.8148290762,NaN,NaN
3,Idaho,Ada,5.4,2.8275698146,4.2961462333,NaN,NaN
4,NaN,Ada County,NaN,NaN,NaN,Idaho,NaN

In [265]:
print(newdf.columns.tolist())

['State_x', 'County', 'Air Pollution - Particulate Matter', 'Poor Physical Health Days', 'Poor Mental Health Days', 'State_y', 'new_pm2.5']

## Because I need to draw scatter plot, first I should transfer all data to numerical value.

In [ ]:
newdf["Poor Physical Health Days"] = pd.to_numeric(
    newdf["Poor Physical Health Days"], errors="coerce"
)
newdf["Poor Mental Health Days"] = pd.to_numeric(
    newdf["Poor Mental Health Days"], errors="coerce"
)


newdf["new_pm2.5"] = pd.to_numeric(newdf["new_pm2.5"], errors="coerce")


newdf = newdf.dropna(
    subset=["new_pm2.5", "Poor Physical Health Days", "Poor Mental Health Days"]
)

## Finally I use plotly package to draw scatter plot.

In [ ]:
fig1 = px.scatter(
    newdf,
    x="new_pm2.5",
    y="Poor Physical Health Days",
    trendline="ols",
    labels={
        "pm25_composite": "PM2.5 composite (µg/m³)",
        "Poor Physical Health Days": "Avg physically unhealthy days",
    },
    title="PM2.5 exposure vs Physically Unhealthy Days",
)
fig1.show()


fig2 = px.scatter(
    newdf,
    x="new_pm2.5",
    y="Poor Mental Health Days",
    trendline="ols",
    labels={
        "pm25_composite": "PM2.5 composite (µg/m³)",
        "Poor Mental Health Days": "Avg mentally unhealthy days",
    },
    title="PM2.5 exposure vs Mentally Unhealthy Days",
)
fig2.show()

### Interpretation of Results & Limitations

The scatter plots of the composite PM₂.₅ index (`new_pm2.5`) versus county-level health outcomes (average physically unhealthy days and average mentally unhealthy days) do **not** show a clear positive relationship as hypothesized. In fact, in both charts the trend appears weak — and in some cases even suggests a negative slope. This null or ambiguous result leads to important caveats and reflections.

**Possible explanations and limitations:** 
- **Measurement and data quality issues.** PM₂.₅ data might not fully capture chronic exposure or acute spikes; the composite index is a simplification (weighted average). Health-days data may rely on survey or reporting methods and may not fully capture pollution-related health burden. Dropping rows with missing or invalid data (e.g. “ND”, “IN”, or NaN) may further bias the sample toward counties with more complete or reliable data.  
- **Cross-sectional nature and lack of temporal dimension.** The analysis is based on a cross-section at one point in time. Air pollution and health effects often accumulate over time (lag effects), which cannot be captured in a cross-section.  

**Conclusion (tentative):**  
The currently observed weak (or non-existent) correlation between PM₂.₅ exposure and health-day outcomes should be interpreted cautiously. It does *not* conclusively rule out health effects from air pollution — rather, it reflects limitations in the data, measurement, and design. Improved data (e.g. longitudinal exposure & health data, individual-level records), controlling for confounders, and more refined analysis would be needed to draw stronger conclusions.  

Nonetheless, reporting this “null / ambiguous” result is important — because it highlights the challenges of ecological, aggregated analyses and underscores the need for more robust, fine-grained data and careful methodological design in environmental health research.